name: my first github actions file
on: [push]
jobs: 
   build: 
     runs-on: ubuntu-latest
     strategy: 
       matrix: 
         python-version: [3.8,3.9]
     steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Neccesary Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name:  Running the tests
        run: python -m pytest test.py
         
